-- begin LIBRARY_FORM
alter table LIBRARY_FORM add constraint FK_LIBRARY_FORM_ON_READER foreign key (READER_ID) references LIBRARY_READER(ID)^
alter table LIBRARY_FORM add constraint FK_LIBRARY_FORM_ON_BOOK foreign key (BOOK_ID) references LIBRARY_BOOK(ID)^
alter table LIBRARY_FORM add constraint FK_LIBRARY_FORM_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references LIBRARY_EMPLOYEE(ID)^
create index IDX_LIBRARY_FORM_ON_READER on LIBRARY_FORM (READER_ID)^
create index IDX_LIBRARY_FORM_ON_BOOK on LIBRARY_FORM (BOOK_ID)^
create index IDX_LIBRARY_FORM_ON_EMPLOYEE on LIBRARY_FORM (EMPLOYEE_ID)^
-- end LIBRARY_FORM

-- begin LIBRARY_EMPLOYEE
alter table LIBRARY_EMPLOYEE add constraint FK_LIBRARY_EMPLOYEE_ON_LIBRARY foreign key (LIBRARY_ID) references LIBRARY_LIBRARY(ID)^
create index IDX_LIBRARY_EMPLOYEE_ON_LIBRARY on LIBRARY_EMPLOYEE (LIBRARY_ID)^
-- end LIBRARY_EMPLOYEE
-- begin LIBRARY_LIBRARY_READER_LINK
alter table LIBRARY_LIBRARY_READER_LINK add constraint FK_LIBREA_ON_READER foreign key (READER_ID) references LIBRARY_READER(ID)^
alter table LIBRARY_LIBRARY_READER_LINK add constraint FK_LIBREA_ON_LIBRARY foreign key (LIBRARY_ID) references LIBRARY_LIBRARY(ID)^
-- end LIBRARY_LIBRARY_READER_LINK

-- begin LIBRARY_BOOK_IN_LIBRARY
alter table LIBRARY_BOOK_IN_LIBRARY add constraint FK_LIBRARY_BOOK_IN_LIBRARY_ON_BOOK foreign key (BOOK_ID) references LIBRARY_BOOK(ID)^
alter table LIBRARY_BOOK_IN_LIBRARY add constraint FK_LIBRARY_BOOK_IN_LIBRARY_ON_LIBRARY foreign key (LIBRARY_ID) references LIBRARY_LIBRARY(ID)^
create index IDX_LIBRARY_BOOK_IN_LIBRARY_ON_BOOK on LIBRARY_BOOK_IN_LIBRARY (BOOK_ID)^
create index IDX_LIBRARY_BOOK_IN_LIBRARY_ON_LIBRARY on LIBRARY_BOOK_IN_LIBRARY (LIBRARY_ID)^
-- end LIBRARY_BOOK_IN_LIBRARY
