alter table LIBRARY_LIBRARY add constraint FK_LIBRARY_LIBRARY_ON_LIBRARY_SISTEM foreign key (LIBRARY_SISTEM_ID) references LIBRARY_LIBRARY_SISTEM(ID);
create index IDX_LIBRARY_LIBRARY_ON_LIBRARY_SISTEM on LIBRARY_LIBRARY (LIBRARY_SISTEM_ID);
