alter table LIBRARY_BOOK_IN_LIBRARY add constraint FK_LIBRARY_BOOK_IN_LIBRARY_ON_BOOK foreign key (BOOK_ID) references LIBRARY_BOOK(ID);
alter table LIBRARY_BOOK_IN_LIBRARY add constraint FK_LIBRARY_BOOK_IN_LIBRARY_ON_LIBRARY foreign key (LIBRARY_ID) references LIBRARY_LIBRARY(ID);
create index IDX_LIBRARY_BOOK_IN_LIBRARY_ON_BOOK on LIBRARY_BOOK_IN_LIBRARY (BOOK_ID);
create index IDX_LIBRARY_BOOK_IN_LIBRARY_ON_LIBRARY on LIBRARY_BOOK_IN_LIBRARY (LIBRARY_ID);
